version: '3.6'
services:
  api-ecommerce:
    build: ./Net.API
    # image: thongnm/api-ecommerce:v1
    container_name: api-ecommerce
    ports:
      - "32771:80"
      - "32770:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_ENVIRONMENT: "Development"
      Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      Kestrel__Certificates__Default__Password: pa55word
    volumes:
      - ./certificate:/https:ro
