version: '3.6'
services:
  api-ecommerce:
    # build: ./NetCore
    build:
      context: ./NetCore
      dockerfile: Dockerfile
    ports:
      - "32771:80"
      - "32770:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_ENVIRONMENT: "Development"
      Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      Kestrel__Certificates__Default__Password: pa55word
    volumes:
      - C:\Users\THONGNM\.aspnet\https:/https:ro