version: '3.6'
services:
  auth-service:
    build: 
      dockerfile: Dockerfile.Auth
    container_name: auth-service
    ports:
      - "32771:80"
      - "32770:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_ENVIRONMENT: "Development"
      Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      Kestrel__Certificates__Default__Password: pa55word
    volumes:
      - ./certificate:/https:ro
  order-service:
    build:
      dockerfile: Dockerfile.Order
    # image: thongnm/api-ecommerce:v1
    container_name: order-service
    ports:
      - "32781:80"
      - "32780:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_ENVIRONMENT: "Development"
      Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      Kestrel__Certificates__Default__Password: pa55word
    volumes:
      - ./certificate:/https:ro
  mssql:
    container_name: mssql_local
    image: mcr.microsoft.com/mssql/server
    environment:
        SA_PASSWORD: "Passw@rd"
        ACCEPT_EULA: "Y"
    ports:
        - 1433:1433
  rediscache:
    image: redis:6.2-alpine
    container_name: redis_local
    ports:
        - '6379:6379'
