version: '3.1'
services:
  postgres:
    container_name: ecommerce
    restart: unless-stopped
    env_file: .env
    image:  postgres:12.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-db}
    ports:
      - '5432:5432'
    networks:
      - ecommerce
networks:
  ecommerce:
    name: ecommerce
    driver: bridge
